version: '3'
services: 
    mongoDb:
        image: mongo
        restart: always
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=example
        
        volumes: 
            - db-volume:/data/db  

    # mongo-experss is an option you can skip this if you want

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
          ME_CONFIG_MONGODB_URL: mongodb://root:example@mongoDb:27017/

    backend:   
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./backend:/app    
        environment: 
            - MONGODB_URI=mongodb+srv://Lavisha:w5p0pDP2q2gVRmyq@cluster0.jp2hm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
            - CHOKIDAR_USEPOLLING=true
            - SG_API=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
        ports:
            - 4000:4000
        depends_on: 
            - mongoDb   
        restart: always    

    frontend:   
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./frontend:/app 
        ports:
            - 3000:3000   
        #request will forward to same url, so we only need /api to distinguish that this request will forward to our backend           
        environment: 
            - REACT_APP_BACKEND_URL=/api
            - CHOKIDAR_USEPOLLING=true
    
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always

volumes: 
    db-volume: